### ISSUE TITLE
Support for other region?

### ISSUE THREAD

**Issue by p1nkyy** [nyuszika7h/hbogosubs#6]
I'm from Asia, so bummed when I tried this but it doesn't work. What needs to be done / given to you in order to make it work in my country? Willing to help. Thank you before.

**Comment by pcroland** [comment]
Which Asian country has a GO site?

**Comment by p1nkyy** [comment]
Indonesia for one. But content is the same with other countries like Singapore or Thailand HBO Go.
Anyway I've found out how to extract it using Developer Mode in Chrome so all is well.
