### ISSUE TITLE
Error after opening the exe

### ISSUE THREAD

**Issue by J1GG4** [nyuszika7h/hbogosubs#8]
I downloaded the new version's exe (1.1.10.), but after opening it, it closes in a second with this error:

![error](https://user-images.githubusercontent.com/27810325/98434050-8616f200-20cc-11eb-865f-b458774e218e.png)

What am I doing wrong? The old version was (is) working perfectly for me.

Thanks! Kösz!

**Comment by pcroland** [comment]
tqdm wasn't included when the exe was built. Here's a fixed version: https://mega.nz/file/XJpwVQTY#EKe46Vl2wXKus1F84jaVBtW5AUzm5De8AYo_V6v8QHs
@nyuszika7h will replace it later.

**Comment by pcroland** [comment]
It's also fixed now on the releases page.
